name: "Build slides"
on:
  # trigger on all pushes
  push:
    branches: ["**"]
  # Allow manual workflow trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build slides
        run: make slides-docker
      - uses: actions/upload-artifact@v3
        with:
          name: slides
          path: ./out/
          if-no-files-found: error
